version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: 'develop'
    versioning-strategy: increase-if-necessary
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "direct"